server:
  port: 8090

spring:
  data:
    mongodb:
      username: mongo_root_4h8j
      password: MG#6yH4$pL9sF2@vB3n
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin